### ISSUE TITLE
Filters are or instead of and?

### ISSUE THREAD

**Issue by dwilliams782** [int128/hide-comment-action#219]
Hi, cool action, thanks! We've just rolled this out to some of our repos to reduce PR noise.

One small observation, I had configured both the author and startsWith and it seems the behaviour is any comment by the author OR comments that start with the given prefix. I expected this to be and rather than or, might be worth adding a note to the readme!

Thanks again, cool project.

**Comment by int128** [comment]
Thank you for your feedback. I fixed the doc as https://github.com/int128/hide-comment-action/issues/219. Feel free to open a pull request for the better doc.
